wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693978698.441991
    t:
      1:
      - 1
      - 30
      - 55
      2:
      - 1
      - 30
      - 55
      3:
      - 23
      4: 3.11.3
      5: 0.15.9
      8:
      - 5
